local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find files" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Live grep" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Find help tags" })
vim.keymap.set("n", "<leader>bf", builtin.current_buffer_fuzzy_find, { desc = "Current buffer fuzzy find" })
vim.keymap.set("n", "<leader>gs", builtin.git_status, { desc = "Git status" })
vim.keymap.set("n", "gr", builtin.lsp_references, { desc = "LSP references" })
vim.keymap.set("n", "gd", builtin.lsp_definitions, { desc = "LSP definitions" })
vim.keymap.set("n", "gi", builtin.lsp_implementations, { desc = "LSP implementations" })
vim.keymap.set("n", "<leader>ld", builtin.diagnostics, { desc = "LSP diagnostics" })

require("telescope").load_extension("fzf")
require("telescope").load_extension("harpoon")
require("telescope").load_extension("session-lens")
require("telescope").load_extension("ui-select")
