import = ["/Users/nmarier/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[scrolling]
history = 100000

[window]
decorations = "full"
opacity = 1
dynamic_title = false

[window.padding]
x = 5
y = 5
