#!/bin/sh

# Source xresources
xrdb ~/.Xresources

# Kill running programs
killall sxhkd
killall dunst
killall polybar

# Bspwm config
bspc config border_width 2
bspc config normal_border_color "#3b4252"
bspc config focused_border_color "#5e81ac"
bspc config window_gap 4

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

autorandr.sh --change
monitor_profile=$(autorandr.sh --detected)

# Set workspaces
case $monitor_profile in
home1)
    bspc monitor "DP-1-2" -d 1 2 3 4
    bspc monitor "DP-1-1" -d 5 6 7
    bspc monitor "DP-1-3" -d 8 9 10
    ;;
home2)
    bspc monitor "DP-1-3" -d 1 2 3 4
    bspc monitor "DP-1-1" -d 5 6 7
    bspc monitor "DP-1-2" -d 8 9 10
    ;;
*)
    notify-send "Monitor config not found" "Could not setup bspwm workspaces for this monitor config"
    ;;
esac

# Autostart programs
$dots/config/polybar/launch.sh
SXHKD_SHELL='/usr/bin/sh' sxhkd &
compton &
dunst &

# Keyboard settings
setxkbmap ca
xset r rate 150 50

# Other settings
feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/desktop/exploring.png

# Bspwm rule examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
