#!/bin/sh

# Source xresources
xrdb ~/.Xresources

# Kill running programs
killall polybar
killall sxhkd

# Bspwm config
bspc config border_width 2
bspc config normal_border_color "#3b4252"
bspc config focused_border_color "#5e81ac"
bspc config window_gap 4

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Set workspaces
case $AUTORANDR_CURRENT_PROFILE in
"home1" | "home2")
    bspc monitor "HDMI-0" -d 1 2 3 4 5
    bspc monitor "DP-4" -d 6 7 8 9 10

    MAIN_MONITOR="HDMI-0" polybar left &
    MAIN_MONITOR="HDMI-0" polybar middle &
    MAIN_MONITOR="HDMI-0" polybar right &

    # Polybar resets the padding
    sleep 1
    bspc config -m "DP-4" top_padding 0
    ;;
"clone-largest")
    bspc monitor "DP-4" -d 1 2 3 4 5 6 7 8 9 10

    MAIN_MONITOR="HDMI-0" polybar left &
    MAIN_MONITOR="HDMI-0" polybar middle &
    MAIN_MONITOR="HDMI-0" polybar right &
    ;;
*)
    # This case will only happen when initially logging in,
    # other executions should always specify an autorandr
    # profile.
    autorandr --change --default default
    ;;
esac

# Autostart programs
SXHKD_SHELL='/usr/bin/sh' sxhkd &
dunst &
picom &

# Keyboard settings
setxkbmap ca
xset r rate 150 50

# Other settings
feh --no-fehbg --bg-fill $HOME/Pictures/wallpapers/desktop/into-the-woods-1920×1080.jpg

# Bspwm rule examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
